inputdirs: [B0, B0WTrigger4GeV, B0WTrigger6GeV]
colors: [864, 632, 418]
markers: [20, 21, 22]
legendnames: ['B^{0}#rightarrowD^{-}#pi^{+}', 'B^{0}#rightarrowD^{-}#pi^{+}, #it{p}_{T}(D^{-}) > 4 GeV/#it{c}', 'B^{0}#rightarrowD^{-}#pi^{+}, #it{p}_{T}(D^{-}) > 6 GeV/#it{c}']

luminosity: 200 #pb-1
ptbinvsLint: 1

outputdir: results/Bhadrons
outputsuffix: _B0diffTrigger