signal:
    inputfile: data/2Prong_3Prong_FilteringSel_LHC18l4b_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_GenPurpose
background:
    inputfile: data/2Prong_3Prong_FilteringSel_LHC18j4_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_GenPurpose

output:
    directory: D0

ptmin: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16]
ptmax: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 24]

varstodraw: [InvMass, fPt, fCosP, fCosPXY, fDecayLength, fNormDecayLengthXY, fImpParProd, fPtMinDau, fd0MinDau]
varmins: [1.6, 0., 0.8, 0.8, 0., 0., -0.01, 0, 0.]
varmaxs: [2.1, 24., 1., 1., 0.25, 30., 0.01, 2., 0.005]

genbranch: GenHadron
seldecays: [2, 1] #D0 and D0bar
massnames: [fInvMassD0, fInvMassD0bar]
recobranch: Charm2Prong
recoselbits: [0, 1]
fidaccbit: 22

applysel:
    doapplysel: False
    selections:
        fPt:
            min: [0., 4., 10.]
            max: [4., 10., 50.]
        fCosP:
            min: [0.8, 0.8, 0.85]
            max: [1., 1., 1.]
        fDecayLength:
            min: [0.05, 0.05, 0.08]
            max: [100., 100., 100.]
        fd0MinDau:
            min: [0.0025, 0.0025, 0.0025]
            max: [100., 100., 100.]
        fPtMinDau:
            min: [0.3, 0.4, 0.4]
            max: [1000., 1000., 1000.]
        fNormDecayLengthXY:
            min: [3., 3., 3.]
            max: [1000., 1000., 1000.]

        
model: models/FONLL-D0-pp14TeV-y05-measbins.txt #pb
BR: 0.0389
fragfrac: 0.542
luminosity: 200 #pb-1
sigmaMB: 57800000000 #pb
fprompt: 0.9 #approximation, to be changed