signal:
    inputfile: D0_Bplus_pp13TeV_LHC18l4b_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_Signal
background:
    inputfile: D0_Bplus_pp13TeV_LHC18l4b_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_Signal

output:
    directory: D0

ptmin: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16]
ptmax: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 24]

varstodraw: [InvMass, fPt, fCosP, fCosPXY, fDecayLength, fNormDecayLengthXY, fImpParProd]
varmins: [1.6, 0., 0.8, 0.8, 0., 0., -0.01]
varmaxs: [2.1, 24., 1., 1., 1., 40., 0.01]

genbranch: GenHadron
seldecays: [2, 1] #D0 and D0bar
massnames: [fInvMassD0, fInvMassD0bar]
recobranch: Charm2Prong
recoselbits: [0, 1]
fidaccbit: 19

applysel:
    doapplysel: False
    selections:
      fPt:
          min: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16]
          max: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 24]
      fCosP:
          min: [0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]
          max: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
      fCosPXY:
          min: [0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]
          max: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
      fDecayLength:
          min: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
          max: [100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.]
      fNormDecayLengthXY:
          min: [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]
          max: [1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.]

model: models/FONLL-D0-pp14TeV-y05-measbins.txt #pb
BR: 0.0389
fragfrac: 0.542
luminosity: 200 #pb-1
sigmaMB: 57800000000 #pb
fprompt: 0.9 #approximation, to be changed