signal:
    inputfile: D0_Bplus_pp13TeV_LHC18l4b_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_Signal
background:
    inputfile: D0_Bplus_pp13TeV_LHC18l4b_improved.root
    inputdir: PWGHF_D2H_CharmTrigger_Signal

output:
    directory: Bplus

ptmin: [0, 2, 4, 6, 8]
ptmax: [2, 4, 6, 8, 12]

varstodraw: [fInvMassBplustoD0pi, fPt, fCosP, fCosPXY, fDecayLength, fNormDecayLengthXY, fImpParProd, fPtD0, fInvMassD0, fNormDecayLengthXYD0]
varmins: [4.8, 0., 0.9, 0.9, 0., 0., -0.01, 0., 1.6, 0.]
varmaxs: [5.6, 12., 1., 1., 1., 40., 0.01, 20., 2.1, 40.]

genbranch: GenHadron
seldecays: [13]
massnames: [fInvMassBplustoD0pi]
recobranch: Beauty3Prong
recoselbits: [9]
fidaccbit: 26

applysel:
    doapplysel: True
    selections:
      fPt:
          min: [0, 2, 4, 6, 8]
          max: [2, 4, 6, 8, 12]
      fPtD0:
          min: [2, 2, 2, 2, 2]
          max: [100, 100, 100, 100, 100]
      fCosPXY:
          min: [0.98, 0.98, 0.99, 0.99, 0.99]
          max: [1.00, 1.00, 1.00, 1.00, 1.00]
      fCosP:
          min: [0.98, 0.98, 0.99, 0.99, 0.99]
          max: [1.00, 1.00, 1.00, 1.00, 1.00]
      fImpParProd:
          min: [-1., -1., -1., -1., -1.]
          max: [0., 0., 0., 0., 0.]
      fNormDecayLengthXYD0:
          min: [5., 5., 5., 5., 5.]
          max: [1000., 1000., 1000., 1000., 1000.]
      fNormDecayLengthXY:
          min: [0., 0., 2., 2., 2.]
          max: [1000., 1000., 1000., 1000., 1000.]
      fInvMassD0:
          min: [1.84, 1.84, 1.84, 1.84, 1.84]
          max: [1.90, 1.90, 1.90, 1.90, 1.90]

model: models/FONLL-B-pp14TeV-y05-widebins.txt #pb
BR: 0.000187109
fragfrac: 0.41
luminosity: 200 #pb-1
sigmaMB: 57800000000 #pb
fprompt: 1.
