import argparse
from ROOT import TFile, TGraphAsymmErrors, TCanvas, TLatex, TLegend, TH1F, TLine
from StyleFormatter import SetGlobalStyle, SetObjectStyle

parser = argparse.ArgumentParser(description='Arguments')
parser.add_argument('infile', metavar='text', default='trigger.root', help='input root file name')
parser.add_argument('--infilePID', metavar='text', default=None, help='input root file name with PID')
parser.add_argument('--infileB', metavar='text', default=None, help='input root file name with B mass requirement')
args = parser.parse_args()

SetGlobalStyle(padbottommargin=0.14, padleftmargin=0.16, padtopmargin=0.035, titleoffsety=1.5)

infile = TFile.Open(args.infile)
gFracTrigEvents2Prong = infile.Get('gFracTrigEvents2Prong')
gFracTrigEvents3Prong = infile.Get('gFracTrigEvents3Prong')
gFracTrigEvents2ProngOr3Prong = infile.Get('gFracTrigEvents2ProngOr3Prong')
gFracTrigEventsDouble2Prong = infile.Get('gFracTrigEventsDouble2Prong')
gFracTrigEventsDouble3Prong = infile.Get('gFracTrigEventsDouble3Prong')
gFracTrigEvents2ProngAnd3Prong = infile.Get('gFracTrigEvents2ProngAnd3Prong')
gPurityTrigEvents2Prong = infile.Get('gPurityTrigEvents2Prong')
gPurityTrigEvents3Prong = infile.Get('gPurityTrigEvents3Prong')
gPurityTrigEvents2ProngOr3Prong = infile.Get('gPurityTrigEvents2ProngOr3Prong')
gPurityTrigEventsDouble2Prong = infile.Get('gPurityTrigEventsDouble2Prong')
gPurityTrigEventsDouble3Prong = infile.Get('gPurityTrigEventsDouble3Prong')
gPurityTrigEvents2ProngAnd3Prong = infile.Get('gPurityTrigEvents2ProngAnd3Prong')
SetObjectStyle(gFracTrigEvents2Prong, color=632, markerstyle=20)
SetObjectStyle(gFracTrigEvents3Prong, color=418, markerstyle=21)
SetObjectStyle(gFracTrigEvents2ProngOr3Prong, color=864, markerstyle=22)
SetObjectStyle(gFracTrigEventsDouble2Prong, color=632, markerstyle=20)
SetObjectStyle(gFracTrigEventsDouble3Prong, color=418, markerstyle=21)
SetObjectStyle(gFracTrigEvents2ProngAnd3Prong, color=864, markerstyle=22)
SetObjectStyle(gPurityTrigEvents2Prong, color=632, markerstyle=20)
SetObjectStyle(gPurityTrigEvents3Prong, color=418, markerstyle=21)
SetObjectStyle(gPurityTrigEvents2ProngOr3Prong, color=864, markerstyle=22)
SetObjectStyle(gPurityTrigEventsDouble2Prong, color=632, markerstyle=20)
SetObjectStyle(gPurityTrigEventsDouble3Prong, color=418, markerstyle=21)
SetObjectStyle(gPurityTrigEvents2ProngAnd3Prong, color=864, markerstyle=22)

if args.infilePID:
    infile = TFile.Open(args.infilePID)
    gFracTrigEvents2ProngPID = infile.Get('gFracTrigEvents2Prong')
    gFracTrigEvents3ProngPID = infile.Get('gFracTrigEvents3Prong')
    gFracTrigEvents2ProngOr3ProngPID = infile.Get('gFracTrigEvents2ProngOr3Prong')
    gFracTrigEventsDouble2ProngPID = infile.Get('gFracTrigEventsDouble2Prong')
    gFracTrigEventsDouble3ProngPID = infile.Get('gFracTrigEventsDouble3Prong')
    gFracTrigEvents2ProngAnd3ProngPID = infile.Get('gFracTrigEvents2ProngAnd3Prong')
    gPurityTrigEvents2ProngPID = infile.Get('gPurityTrigEvents2Prong')
    gPurityTrigEvents3ProngPID = infile.Get('gPurityTrigEvents3Prong')
    gPurityTrigEvents2ProngOr3ProngPID = infile.Get('gPurityTrigEvents2ProngOr3Prong')
    gPurityTrigEventsDouble2ProngPID = infile.Get('gPurityTrigEventsDouble2Prong')
    gPurityTrigEventsDouble3ProngPID = infile.Get('gPurityTrigEventsDouble3Prong')
    gPurityTrigEvents2ProngAnd3ProngPID = infile.Get('gPurityTrigEvents2ProngAnd3Prong')
    SetObjectStyle(gFracTrigEvents2ProngPID, color=632, markerstyle=24)
    SetObjectStyle(gFracTrigEvents3ProngPID, color=418, markerstyle=25)
    SetObjectStyle(gFracTrigEvents2ProngOr3ProngPID, color=864, markerstyle=26)
    SetObjectStyle(gFracTrigEventsDouble2ProngPID, color=632, markerstyle=24)
    SetObjectStyle(gFracTrigEventsDouble3ProngPID, color=418, markerstyle=25)
    SetObjectStyle(gFracTrigEvents2ProngAnd3ProngPID, color=864, markerstyle=26)
    SetObjectStyle(gPurityTrigEvents2ProngPID, color=632, markerstyle=24)
    SetObjectStyle(gPurityTrigEvents3ProngPID, color=418, markerstyle=25)
    SetObjectStyle(gPurityTrigEvents2ProngOr3ProngPID, color=864, markerstyle=26)
    SetObjectStyle(gPurityTrigEventsDouble2ProngPID, color=632, markerstyle=24)
    SetObjectStyle(gPurityTrigEventsDouble3ProngPID, color=418, markerstyle=25)
    SetObjectStyle(gPurityTrigEvents2ProngAnd3ProngPID, color=864, markerstyle=26)

if args.infileB:
    infile = TFile.Open(args.infileB)
    gFracTrigEvents2ProngB = infile.Get('gFracTrigEvents2Prong')
    gFracTrigEvents3ProngB = infile.Get('gFracTrigEvents3Prong')
    gFracTrigEvents2ProngOr3ProngB = infile.Get('gFracTrigEvents2ProngOr3Prong')
    gFracTrigEventsDouble2ProngB = infile.Get('gFracTrigEventsDouble2Prong')
    gFracTrigEventsDouble3ProngB = infile.Get('gFracTrigEventsDouble3Prong')
    gFracTrigEvents2ProngAnd3ProngB = infile.Get('gFracTrigEvents2ProngAnd3Prong')
    gPurityTrigEvents2ProngB = infile.Get('gPurityTrigEvents2Prong')
    gPurityTrigEvents3ProngB = infile.Get('gPurityTrigEvents3Prong')
    gPurityTrigEvents2ProngOr3ProngB = infile.Get('gPurityTrigEvents2ProngOr3Prong')
    gPurityTrigEventsDouble2ProngB = infile.Get('gPurityTrigEventsDouble2Prong')
    gPurityTrigEventsDouble3ProngB = infile.Get('gPurityTrigEventsDouble3Prong')
    gPurityTrigEvents2ProngAnd3ProngB = infile.Get('gPurityTrigEvents2ProngAnd3Prong')
    SetObjectStyle(gFracTrigEvents2ProngB, color=632, markerstyle=24)
    SetObjectStyle(gFracTrigEvents3ProngB, color=418, markerstyle=25)
    SetObjectStyle(gFracTrigEvents2ProngOr3ProngB, color=864, markerstyle=26)
    SetObjectStyle(gFracTrigEventsDouble2ProngB, color=632, markerstyle=24)
    SetObjectStyle(gFracTrigEventsDouble3ProngB, color=418, markerstyle=25)
    SetObjectStyle(gFracTrigEvents2ProngAnd3ProngB, color=864, markerstyle=26)
    SetObjectStyle(gPurityTrigEvents2ProngB, color=632, markerstyle=24)
    SetObjectStyle(gPurityTrigEvents3ProngB, color=418, markerstyle=25)
    SetObjectStyle(gPurityTrigEvents2ProngOr3ProngB, color=864, markerstyle=26)
    SetObjectStyle(gPurityTrigEventsDouble2ProngB, color=632, markerstyle=24)
    SetObjectStyle(gPurityTrigEventsDouble3ProngB, color=418, markerstyle=25)
    SetObjectStyle(gPurityTrigEvents2ProngAnd3ProngB, color=864, markerstyle=26)

legSingle = TLegend(0.2, 0.2, 0.4, 0.4)
legSingle.SetTextSize(0.045)
legSingle.SetBorderSize(0)
legSingle.SetHeader('Events with at least:')
legSingle.SetFillStyle(0)
legDouble = legSingle.Clone()
legSingle.AddEntry(gFracTrigEvents2Prong, 'one 2-prong', 'p')
legSingle.AddEntry(gFracTrigEvents3Prong, 'one 3-prong', 'p')
legSingle.AddEntry(gFracTrigEvents2ProngOr3Prong, 'one 2-prong or one 3-prong', 'p')
legDouble.AddEntry(gFracTrigEventsDouble2Prong, 'two 2-prong', 'p')
legDouble.AddEntry(gFracTrigEventsDouble3Prong, 'two 3-prong', 'p')
legDouble.AddEntry(gFracTrigEvents2ProngAnd3Prong, 'one 2-prong and one 3-prong', 'p')

lat = TLatex()
lat.SetNDC()
lat.SetTextColor(1)
lat.SetTextSize(0.045)
lat.SetTextFont(42)

cEffSingle = TCanvas('cEffSingle', '', 500, 500)
cEffSingle.DrawFrame(-0.5, 1.e-8, 10.5, 1., ';#it{p}_{T} (GeV/#it{c}) > ;Fraction of events;')
cEffSingle.SetLogy()
cEffSingle.SetGrid()
gFracTrigEvents2Prong.Draw('P')
gFracTrigEvents3Prong.Draw('P')
gFracTrigEvents2ProngOr3Prong.Draw('P')
legSingle.Draw()
if args.infilePID:
    gFracTrigEvents2ProngPID.Draw('P')
    gFracTrigEvents3ProngPID.Draw('P')
    gFracTrigEvents2ProngOr3ProngPID.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o PID')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ PID')
if args.infileB:
    gFracTrigEvents2ProngB.Draw('P')
    gFracTrigEvents3ProngB.Draw('P')
    gFracTrigEvents2ProngOr3ProngB.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o B mass')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ B mass')

cEffDouble = TCanvas('cEffDouble', '', 500, 500)
cEffDouble.DrawFrame(-0.5, 1.e-8, 10.5, 1., ';#it{p}_{T} (GeV/#it{c}) > ;Fraction of events;')
cEffDouble.SetLogy()
cEffDouble.SetGrid()
gFracTrigEventsDouble2Prong.Draw('P')
gFracTrigEventsDouble3Prong.Draw('P')
gFracTrigEvents2ProngAnd3Prong.Draw('P')
legDouble.Draw()
if args.infilePID:
    gFracTrigEventsDouble2ProngPID.Draw('P')
    gFracTrigEventsDouble3ProngPID.Draw('P')
    gFracTrigEvents2ProngAnd3ProngPID.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o PID')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ PID')
if args.infileB:
    gFracTrigEventsDouble2ProngB.Draw('P')
    gFracTrigEventsDouble3ProngB.Draw('P')
    gFracTrigEvents2ProngAnd3ProngB.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o B mass')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ B mass')

cPuritySingle = TCanvas('cPuritySingle', '', 500, 500)
cPuritySingle.DrawFrame(-0.5, 1.e-5, 10.5, 10., ';#it{p}_{T} (GeV/#it{c}) > ;Purity;')
cPuritySingle.SetLogy()
cPuritySingle.SetGrid()
gPurityTrigEvents2Prong.Draw('P')
gPurityTrigEvents3Prong.Draw('P')
gPurityTrigEvents2ProngOr3Prong.Draw('P')
legSingle.Draw()
if args.infilePID:
    gPurityTrigEvents2ProngPID.Draw('P')
    gPurityTrigEvents3ProngPID.Draw('P')
    gPurityTrigEvents2ProngOr3ProngPID.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o PID')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ PID')
if args.infileB:
    gPurityTrigEvents2ProngB.Draw('P')
    gPurityTrigEvents3ProngB.Draw('P')
    gPurityTrigEvents2ProngOr3ProngB.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o B mass')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ B mass')

cPurityDouble = TCanvas('cPurityDouble', '', 500, 500)
cPurityDouble.DrawFrame(-0.5, 1.e-8, 10.5, 10., ';#it{p}_{T} (GeV/#it{c}) > ;Purity;')
cPurityDouble.SetLogy()
cPurityDouble.SetGrid()
gPurityTrigEventsDouble2Prong.Draw('P')
gPurityTrigEventsDouble3Prong.Draw('P')
gPurityTrigEvents2ProngAnd3Prong.Draw('P')
legDouble.Draw()
if args.infilePID:
    gPurityTrigEventsDouble2ProngPID.Draw('P')
    gPurityTrigEventsDouble3ProngPID.Draw('P')
    gPurityTrigEvents2ProngAnd3ProngPID.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o PID')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ PID')
if args.infilePID:
    gPurityTrigEventsDouble2ProngB.Draw('P')
    gPurityTrigEventsDouble3ProngB.Draw('P')
    gPurityTrigEvents2ProngAnd3ProngB.Draw('P')
    lat.DrawLatex(0.5, 0.9, 'full markers: w/o B mass')
    lat.DrawLatex(0.5, 0.84, 'open markers: w/ B mass')

outFileNameSingle = args.infile.replace('.root', '_Eff_SingleTrigger.pdf')
cEffSingle.SaveAs(outFileNameSingle)
outFileNameDouble = args.infile.replace('.root', '_Eff_DoubleTrigger.pdf')
cEffDouble.SaveAs(outFileNameDouble)

outFileNameSingle = args.infile.replace('.root', '_Purity_SingleTrigger.pdf')
cPuritySingle.SaveAs(outFileNameSingle)
outFileNameDouble = args.infile.replace('.root', '_Purity_DoubleTrigger.pdf')
cPurityDouble.SaveAs(outFileNameDouble)

input()