runtype: grid #local, test, grid
pathtolocalAOD: '.'
system: pp
datadir: /alice/sim/2018/LHC18l4b
datapattern: AOD
gridworkdir: CharmTriggerEfficiency
splitmaxinputfilenum: 50
AliPhysicVersion: vAN-20200108_ROOT6-1
runs: [286350]

improverfiles:
    currentresol: $ALICE_PHYSICS/PWGHF/vertexingHF/upgrade/ITSgraphs_Current.root
    upgraderesol: $ALICE_PHYSICS/PWGHF/vertexingHF/upgrade/ITSgraphs_NewAll-X0.3-Res4um.root

cuts:
    applycuts: 0
    cutfile: alien:///alice/cern.ch/user/f/fgrosa/CutObjects/pp13TevUpgr/D0DplusDsLcPreselectionCuts.root

taskoptions:
    writeonlysignal: 1
    enableD0: 1
    enableDplus: 1
    enableDs: 1
    enableLc: 1
    enableDstar: 0
    enableLc2V0: 0
    enableBplus: 0
    enableB0: 0
    enableBs: 0
    enableLb: 0
