runtype: local #local, test, grid
pathtolocalAOD: 'AODfiles/LHC18l4b'
system: pp
datadir: /alice/sim/2018/LHC18l4b
datapattern: AOD
gridworkdir: CharmTriggerEfficiency
splitmaxinputfilenum: 50
AliPhysicVersion: vAN-20200506_ROOT6-1
runs: [286350]

improverfiles:
    currentresol: $ALICE_PHYSICS/PWGHF/vertexingHF/upgrade/ITSgraphs_Current.root
    upgraderesol: $ALICE_PHYSICS/PWGHF/vertexingHF/upgrade/ITSgraphs_NewAll-X0.3-Res4um.root

cuts:
    applycuts: 0
    cutfile: alien:///alice/cern.ch/user/f/fgrosa/CutObjects/pp13TevUpgr/D0DplusDsLcPreselectionCuts.root

taskoptions:
    writeonlysignal: 0
    enableD0: 0
    enableDplus: 0
    enableDs: 0
    enableLc: 0
    enableDstar: 0
    enableLc2V0: 0
    enableBplus: 1
    enableB0: 1
    enableBs: 1
    enableLb: 1
